# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11qtrvPQCXzRxwHcC8qyc0ppRiAejtxAJ
"""

import pandas as pd
df = pd.read_csv (r'Teacher_salary_csv.csv')
df1 = pd.DataFrame(columns=['feed'])
df1['feed']=df['Average feedback']
df2=df1.dropna(axis=0, how='any')
print(df2)
Q1 = df2.quantile(0.25)
Q3 = df2.quantile(0.75)
IQR = Q3 - Q1
print(IQR)
print(df2.query('( @Q1 - 1.5 * @IQR) <= feed <= (@Q3 + 1.5 * @IQR)'))
df2['mean']=df2['feed'].mean()
df2['std']=df2['feed'].std()
df2['zscore']=(df2['feed']-df2['mean'])/df2['std']
print(df2)
print(df2.query('-3 <= feed <= 3'))







